feat: modify source files before compilation
ng-packagr/ng-packagr pull request #2306
Opened 2022-04-14 23:25 UTC by lekhmanrus

## I'm submitting a...

```
[ ] Bug Fix
[x] Feature
[ ] Other (Refactoring, Added tests, Documentation, ...)
```

## Checklist

- [x] Commit Messages follow the [Conventional Commits](https://conventionalcommits.org/) pattern
  - A feature commit message is prefixed "feat:"
  - A bugfix commit message is prefixed "fix:"
- [ ] Tests for the changes have been added

## Description

Ability to modify source files before compilation.
E.g.: might be used to compile pug files to html.
Probably related to #1619.
NgPackage config can have `resourceReader` string - path to exported JS
function responsible for reading sources code files.

### Use Case
* `ng-package.json`:
  ```json
  {
    "$schema": "../../node_modules/ng-packagr/ng-package.schema.json",
    "resourceReader": "./a.js",
    ...
  }
  ```

* `a.js`:
```js
const path = require('path');
const pug = require('pug');

module.exports = async (
  fileName,
  compilerHost,
  stylesheetProcessor
) => {
  let content;
  if (/(?:html?|svg)$/.test(path.extname(fileName))) {
    // template
    content = compilerHost.readFile.call(this, fileName);
  }
  else if (/(?:pug)$/.test(path.extname(fileName))) {
    // template
    var pugSource = compilerHost.readFile.call(this, fileName);
    content = pug.compile(pugSource)();
  }
  else {
    // stylesheet
    content = await stylesheetProcessor.process({
      filePath: fileName,
      content: compilerHost.readFile.call(this, fileName),
    });
  }

  return content;
};
```

closes #1601

## Does this PR introduce a breaking change?

```
[ ] Yes
[x] No
```

2022-04-16 14:53 UTC, SchnWalter requested changes

2022-04-18 23:57 UTC, lekhmanrus commented on src/lib/ts/cache-compiler-host.ts
> +        if (ngPackage?.resourceReader) {
Sounds good! Added `TemplateProcessor` instead and added `pug` support.

2022-04-18 23:57 UTC, lekhmanrus commented on src/lib/ts/cache-compiler-host.ts
> -          cache.content = await stylesheetProcessor.process({
Currently, `stylesheetProcessor.process` inside `readResource()` transforms style **files** to CSS; and `stylesheetProcessor.process` inside `transformResource()` transforms **inline** styles to CSS.
I'm not sure, is it safe to make that change?

2022-10-07 13:37 UTC, alan-agius4 commented
@lekhmanrus, thanks for this PR however first party support fur PUG is not something that is desired.

2022-10-07 13:37 UTC, closed without merging